version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - "3030:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start"
