services:
  app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - "3030:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start"

  api:
    build: ./docker/api
    ports:
      - "8008:8080"
    volumes:
      - ./api:/app
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    build: ./docker/mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3309:3306
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-u",
          "user",
          "--password=password",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 3s

volumes:
  mysql-data:
    driver: local
